[package]
name = "world_renderer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3.26"
once_cell = "1.18.0"
rand = "0.8.5"
noise = "0.8.2"